/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cadastro.java
 *
 * Created on 18/03/2013, 00:57:11
 */

package controleestoque.tela;

import controleestoque.BO.produtoBO;
import controleestoque.bean.produtoEntity;
import controleestoque.crud.produtoDAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author re
 */
public class cadastro extends javax.swing.JDialog {

    private produtoDAO produtoDAO;
    private produtoEntity produtoEntity;
    private produtoBO produtoBO;

    private boolean alterar = false;
    /** Creates new form cadastro */
    public cadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        produtoDAO = new produtoDAO();
        produtoEntity = new produtoEntity();
        produtoBO = new produtoBO();

        initComponents();

    }

    cadastro(JFrame parent, boolean modal, produtoEntity produto) {

        super(parent, modal);
        produtoDAO = new produtoDAO();
        produtoEntity = produto;
        produtoBO = new produtoBO();

        initComponents();

                JTFCodigo.setText(produtoEntity.getId().toString());
                JTFDescricao.setText(produtoEntity.getDescricaoProduto());
                JTFCodigoBarras.setText(produtoEntity.getCodigoBarras());
                JCBUnidade.setSelectedIndex(0);
                JCBCategoria.setSelectedIndex(0);
                JTFMarca.setText(produtoEntity.getMarca());
                JTFModelo.setText(produtoEntity.getModelo());
                JTFUnidadeEstoque.setText(produtoEntity.getUnidadeEstoque().toString());
                JTAAplicacao.setText(produtoEntity.getAplicacao());
                JTADetalhe.setText(produtoEntity.getDetalhe());
                JTFUltimoCusto.setText(produtoEntity.getUltimoCusto().toString());
                JTFValorVenda.setText(produtoEntity.getValorVenda().toString());
      alterar = true;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBSalvar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        JLCodigo = new javax.swing.JLabel();
        JTFCodigo = new javax.swing.JTextField();
        JLDescricao = new javax.swing.JLabel();
        JTFDescricao = new javax.swing.JTextField();
        JLCodigoBarras = new javax.swing.JLabel();
        JTFCodigoBarras = new javax.swing.JTextField();
        JLUnidade = new javax.swing.JLabel();
        JCBUnidade = new javax.swing.JComboBox();
        JLCategoria = new javax.swing.JLabel();
        JCBCategoria = new javax.swing.JComboBox();
        JLMarca = new javax.swing.JLabel();
        JTFMarca = new javax.swing.JTextField();
        JLModelo = new javax.swing.JLabel();
        JTFModelo = new javax.swing.JTextField();
        JLAplicacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAAplicacao = new javax.swing.JTextArea();
        JLDetalhe = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTADetalhe = new javax.swing.JTextArea();
        JPValores = new javax.swing.JPanel();
        JLUltimoCusto = new javax.swing.JLabel();
        JTFUltimoCusto = new javax.swing.JTextField();
        JLValorVenda = new javax.swing.JLabel();
        JTFValorVenda = new javax.swing.JTextField();
        JLUnidadeEstoque = new javax.swing.JLabel();
        JTFUnidadeEstoque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Produto");
        setResizable(false);

        JBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/save.png"))); // NOI18N
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/cancelar.png"))); // NOI18N
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JLCodigo.setText("Código");

        JTFCodigo.setEnabled(false);

        JLDescricao.setText("Descrição do Produto");

        JLCodigoBarras.setText("Código de Barras");

        JLUnidade.setText("Unidade");

        JCBUnidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Peça", "Saco", "Kg", "Maço" }));

        JLCategoria.setText("Categoria");

        JCBCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alimento", "Equip." }));

        JLMarca.setText("Marca");

        JLModelo.setText("Modelo");

        JLAplicacao.setText("Aplicação");

        JTAAplicacao.setColumns(20);
        JTAAplicacao.setRows(5);
        jScrollPane1.setViewportView(JTAAplicacao);

        JLDetalhe.setText("Detalhes Técnicos");

        JTADetalhe.setColumns(20);
        JTADetalhe.setRows(5);
        jScrollPane2.setViewportView(JTADetalhe);

        JPValores.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        JLUltimoCusto.setText("Último Custo (R$)");

        JTFUltimoCusto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JTFUltimoCusto.setText("0,00");

        JLValorVenda.setText("Valor Venda (R$)");

        JTFValorVenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JTFValorVenda.setText("0,00");

        javax.swing.GroupLayout JPValoresLayout = new javax.swing.GroupLayout(JPValores);
        JPValores.setLayout(JPValoresLayout);
        JPValoresLayout.setHorizontalGroup(
            JPValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTFUltimoCusto, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(JLUltimoCusto)
                    .addComponent(JLValorVenda)
                    .addComponent(JTFValorVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPValoresLayout.setVerticalGroup(
            JPValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLUltimoCusto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFUltimoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLValorVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        JLUnidadeEstoque.setText("Unid. Estoque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(JBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLCodigo)
                                .addGap(39, 39, 39)
                                .addComponent(JLDescricao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLCodigoBarras)
                                .addGap(154, 154, 154)
                                .addComponent(JLUnidade)
                                .addGap(64, 64, 64)
                                .addComponent(JLCategoria))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JTFMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTFCodigoBarras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addComponent(JLAplicacao, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(JLMarca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JLModelo)
                                        .addGap(107, 107, 107)
                                        .addComponent(JLUnidadeEstoque))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JCBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JTFUnidadeEstoque))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                            .addComponent(JLDetalhe)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JPValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JBCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(JBSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLCodigo)
                            .addComponent(JLDescricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLCodigoBarras)
                            .addComponent(JLUnidade)
                            .addComponent(JLCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLMarca)
                            .addComponent(JLModelo)
                            .addComponent(JLUnidadeEstoque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFUnidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JPValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLAplicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLDetalhe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        salvar();
        
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        alterar = false;
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cadastro dialog = new cadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBSalvar;
    private javax.swing.JComboBox JCBCategoria;
    private javax.swing.JComboBox JCBUnidade;
    private javax.swing.JLabel JLAplicacao;
    private javax.swing.JLabel JLCategoria;
    private javax.swing.JLabel JLCodigo;
    private javax.swing.JLabel JLCodigoBarras;
    private javax.swing.JLabel JLDescricao;
    private javax.swing.JLabel JLDetalhe;
    private javax.swing.JLabel JLMarca;
    private javax.swing.JLabel JLModelo;
    private javax.swing.JLabel JLUltimoCusto;
    private javax.swing.JLabel JLUnidade;
    private javax.swing.JLabel JLUnidadeEstoque;
    private javax.swing.JLabel JLValorVenda;
    private javax.swing.JPanel JPValores;
    private javax.swing.JTextArea JTAAplicacao;
    private javax.swing.JTextArea JTADetalhe;
    private javax.swing.JTextField JTFCodigo;
    private javax.swing.JTextField JTFCodigoBarras;
    private javax.swing.JTextField JTFDescricao;
    private javax.swing.JTextField JTFMarca;
    private javax.swing.JTextField JTFModelo;
    private javax.swing.JTextField JTFUltimoCusto;
    private javax.swing.JTextField JTFUnidadeEstoque;
    private javax.swing.JTextField JTFValorVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void salvar() {

        try{
        produtoEntity.setDescricaoProduto(JTFDescricao.getText());
        produtoEntity.setCodigoBarras(JTFCodigoBarras.getText());
        produtoEntity.setUnidade((String) JCBUnidade.getSelectedItem());
        produtoEntity.setCategoria((String) JCBCategoria.getSelectedItem());
        produtoEntity.setMarca(JTFMarca.getText());
        produtoEntity.setModelo(JTFModelo.getText());
        produtoEntity.setUnidadeEstoque(Integer.parseInt(JTFUnidadeEstoque.getText()));
        produtoEntity.setAplicacao(JTAAplicacao.getText());
        produtoEntity.setDetalhe(JTADetalhe.getText());
        produtoEntity.setUltimoCusto(Double.parseDouble(JTFUltimoCusto.getText().replace(',', '.')));
        produtoEntity.setValorVenda(Double.parseDouble(JTFValorVenda.getText().replace(',', '.')));

        if(produtoBO.validar(produtoEntity)){
if(produtoEntity.getId()==null){
            produtoDAO.novo(produtoEntity);
            
            if(0==JOptionPane.showOptionDialog(null, "Deseja Cadastrar outro produto?", null, JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Sim","Não"}, null)){
                produtoEntity = null;
                produtoEntity = new produtoEntity();

                JTFCodigo.setText("");
                JTFDescricao.setText("");
                JTFCodigoBarras.setText("");
                JCBUnidade.setSelectedIndex(0);
                JCBCategoria.setSelectedIndex(0);
                JTFMarca.setText("");
                JTFModelo.setText("");
                JTFUnidadeEstoque.setText("");
                JTAAplicacao.setText("");
                JTADetalhe.setText("");
                JTFUltimoCusto.setText("0,00");
                JTFValorVenda.setText("0,00");

            }else{
                this.dispose();
            }

        }else{

            produtoDAO.atualizar(produtoEntity);
            this.dispose();
        }
        alterar=false;
        
        }

        }catch(NumberFormatException ex){

            JOptionPane.showMessageDialog(null, "Formato de numero errado", "Erro", JOptionPane.ERROR_MESSAGE);

        }

    }

    public boolean getAlterar(){
        return alterar;
    }

}
