/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * relatorio.java
 *
 * Created on 04/04/2013, 21:22:34
 */

package controleestoque.tela;

import com.toedter.calendar.JDateChooser;
import controleestoque.bean.produtoMovimentoEntity;
import controleestoque.crud.produtoMovimentoDAO;
import controleestoque.util.gerarPDF;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author re
 */
public class relatorio extends javax.swing.JDialog {
    private JDateChooser calendarioInicial;
    private JDateChooser calendarioFinal;
    private JLabel JLAte;

    private boolean stop = true;
    private Thread thread;
    private listar listar;

    /** Creates new form relatorio */
    public relatorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        calendarioInicial = new JDateChooser(new Date());
        calendarioInicial.setBounds(10, 10, 100, 20);
        calendarioInicial.setMaxSelectableDate(new Date());

        JLAte = new JLabel("até");
        JLAte.setBounds(120, 10, 30, 20);

        calendarioFinal = new JDateChooser(new Date());
        calendarioFinal.setBounds(150, 10, 100, 20);
        calendarioFinal.setMaxSelectableDate(new Date());

       JPGeral.add(calendarioInicial);
       JPGeral.add(calendarioFinal);
       JPGeral.add(JLAte);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPTipo = new javax.swing.JPanel();
        JRBSaida = new javax.swing.JRadioButton();
        JRBEntrada = new javax.swing.JRadioButton();
        JPGeral = new javax.swing.JPanel();
        JTFCodigo = new javax.swing.JTextField();
        JLCodigo = new javax.swing.JLabel();
        JBPesquisa = new javax.swing.JButton();
        JBGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        JPTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));

        JRBSaida.setText("por Saída");
        JRBSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBSaidaActionPerformed(evt);
            }
        });

        JRBEntrada.setText("por Entrada");
        JRBEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPTipoLayout = new javax.swing.GroupLayout(JPTipo);
        JPTipo.setLayout(JPTipoLayout);
        JPTipoLayout.setHorizontalGroup(
            JPTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTipoLayout.createSequentialGroup()
                .addGroup(JPTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRBSaida)
                    .addComponent(JRBEntrada))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        JPTipoLayout.setVerticalGroup(
            JPTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTipoLayout.createSequentialGroup()
                .addComponent(JRBSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRBEntrada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPGeral.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        JLCodigo.setText("Código produto:");

        JBPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lupa.png"))); // NOI18N
        JBPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPGeralLayout = new javax.swing.GroupLayout(JPGeral);
        JPGeral.setLayout(JPGeralLayout);
        JPGeralLayout.setHorizontalGroup(
            JPGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPGeralLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(JLCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        JPGeralLayout.setVerticalGroup(
            JPGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPGeralLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(JPGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLCodigo)
                        .addComponent(JTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JBPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        JBGerar.setText("Gerar Relatorio");
        JBGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(JPGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JBGerar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(JPGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JPTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(JBGerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRBSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBSaidaActionPerformed

        JRBSaida.setSelected(true);
        JRBEntrada.setSelected(false);
    }//GEN-LAST:event_JRBSaidaActionPerformed

    private void JRBEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBEntradaActionPerformed
        JRBEntrada.setSelected(true);
        JRBSaida.setSelected(false);
    }//GEN-LAST:event_JRBEntradaActionPerformed

    private void JBPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPesquisaActionPerformed

         listar = new listar((JFrame) this.getParent(), true);
            listar.selecionar();
            stop = false;
            start();
            listar.show();

    }//GEN-LAST:event_JBPesquisaActionPerformed

    private void JBGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGerarActionPerformed
        try {
            gerar();
        } catch (IOException ex) {
            Logger.getLogger(relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_JBGerarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                relatorio dialog = new relatorio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGerar;
    private javax.swing.JButton JBPesquisa;
    private javax.swing.JLabel JLCodigo;
    private javax.swing.JPanel JPGeral;
    private javax.swing.JPanel JPTipo;
    private javax.swing.JRadioButton JRBEntrada;
    private javax.swing.JRadioButton JRBSaida;
    private javax.swing.JTextField JTFCodigo;
    // End of variables declaration//GEN-END:variables

public void gerar() throws IOException{

    List<produtoMovimentoEntity> all;
    Integer tipo, idProduto = null;
    String inicio, fim;

    if(!JRBEntrada.isSelected() && !JRBSaida.isSelected()){
        JOptionPane.showMessageDialog(this, "Selecione o tipo de busca.");
        return;
    }

    tipo = JRBEntrada.isSelected() ? 0 : 1;

    try{
    inicio = (new SimpleDateFormat("yyyy-MM-dd").format(calendarioInicial.getDate()));
    fim = (new SimpleDateFormat("yyyy-MM-dd").format(calendarioFinal.getDate()));
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, "Foi encontrado um erro nas datas informadas");
        return;
    }

    if(!JTFCodigo.getText().equalsIgnoreCase("")){
        try{
            idProduto = Integer.parseInt(JTFCodigo.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Cógigo informado esta no formato errado", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    produtoMovimentoDAO produtoMovimentoDAO = new produtoMovimentoDAO();
    all = produtoMovimentoDAO.relatorio(tipo, idProduto, inicio, fim);

    gerarPDF pdf = new gerarPDF();
    pdf.criar(all);


}

    public void start(){

		thread=new Thread(new Runnable(){
			public void run(){
				try{
				while(!stop){
                                    if(listar.getProdutoSelecionado().getId()!=null){
                                        stop = true;
                                        JTFCodigo.setText(listar.getProdutoSelecionado().getId().toString());
                                        listar = null;
                                        thread.stop();
                                    }
                                    thread.sleep(100);
				}
			}catch(Exception e){
                                e.printStackTrace();
			}

		}
        });
		thread.start();
	}

}
