
/*
 * principal.java
 *
 * Created on 17/03/2013, 12:58:13
 */

package validadorcmc7;

import validadorcmc7.util.bancos;
import validadorcmc7.util.verificar;

/**
 *
 * @author re
 */
public class principal extends javax.swing.JFrame {

    /** Creates new form principal */
    public principal() {
        initComponents();

        JTFCampo1.setText("");
        JTFCampo2.setText("");
        JTFCampo3.setText("");

        JTFBanco.setText("");
        JTFBanco.setEditable(false);

        JTFAgencia.setText("");
        JTFAgencia.setEditable(false);

        JLAviso.setVisible(false);

        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPValidar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JLCMC7 = new javax.swing.JLabel();
        JTFCampo1 = new javax.swing.JTextField();
        JTFCampo2 = new javax.swing.JTextField();
        JTFCampo3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        JBValidar = new javax.swing.JButton();
        JLAviso = new javax.swing.JLabel();
        JLBanco = new javax.swing.JLabel();
        JLAgencia = new javax.swing.JLabel();
        JTFAgencia = new javax.swing.JTextField();
        JTFBanco = new javax.swing.JTextField();
        JBLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validador CMC7");
        setResizable(false);

        JLCMC7.setText("Valor CMC7: ");

        JTFCampo1.setText("12345678");

        JTFCampo2.setText("1234567891");

        JTFCampo3.setText("123456789123");

        JBValidar.setText("Validar");
        JBValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBValidarActionPerformed(evt);
            }
        });

        JLAviso.setText("Cheque Valido");

        JLBanco.setText("Banco:");

        JLAgencia.setText("Agencia:");

        JTFAgencia.setText("jTextField4");

        JTFBanco.setText("jTextField5");

        JBLimpar.setText("Limpar");
        JBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLAgencia)
                                    .addComponent(JLBanco))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTFCampo1)
                            .addComponent(JLCMC7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(JTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBValidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(JLAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(JLCMC7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBLimpar)
                    .addComponent(JBValidar)
                    .addComponent(JLAviso))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBanco)
                    .addComponent(JTFBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLAgencia)
                    .addComponent(JTFAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTPValidar.addTab("Validar", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPValidar, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jTPValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimparActionPerformed

        JTFCampo1.setText("");
        JTFCampo2.setText("");
        JTFCampo3.setText("");

        JTFBanco.setText("");

        JTFAgencia.setText("");

        JLAviso.setVisible(false);

        JTFCampo1.requestFocus();

    }//GEN-LAST:event_JBLimparActionPerformed

    private void JBValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBValidarActionPerformed

        verificar verificar = new verificar();
        bancos banco = new bancos();
        String nome = "";

        boolean valido = verificar.validarCMC7(JTFCampo1.getText()+ JTFCampo2.getText()+ JTFCampo3.getText());

        if(valido){
            JLAviso.setText("Cheque Valido.");
        }else{
            JLAviso.setText("Cheque Invalido.");
        }
        try{
        JLAviso.setVisible(true);

        if(JTFCampo1.getText().charAt(3)=='-'){
            nome = banco.nome(JTFCampo1.getText().substring(0, 5));
            JTFAgencia.setText(JTFCampo1.getText().substring(5,JTFCampo1.getText().length()-1));

        }else{
            nome = banco.nome(JTFCampo1.getText().substring(0, 3));
            JTFAgencia.setText(JTFCampo1.getText().substring(3,JTFCampo1.getText().length()-1));
        }

        JTFBanco.setText(nome);
        }catch(StringIndexOutOfBoundsException ex){
            JLAviso.setVisible(false);
        }
    }//GEN-LAST:event_JBValidarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBLimpar;
    private javax.swing.JButton JBValidar;
    private javax.swing.JLabel JLAgencia;
    private javax.swing.JLabel JLAviso;
    private javax.swing.JLabel JLBanco;
    private javax.swing.JLabel JLCMC7;
    private javax.swing.JTextField JTFAgencia;
    private javax.swing.JTextField JTFBanco;
    private javax.swing.JTextField JTFCampo1;
    private javax.swing.JTextField JTFCampo2;
    private javax.swing.JTextField JTFCampo3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTPValidar;
    // End of variables declaration//GEN-END:variables

}
